name: valorant_intel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.2
  go_router: ^15.1.3
  hydrated_bloc: ^10.0.0
  intl: any
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.4+1
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  build_runner: ^2.3.3
  bloc_test: ^10.0.0
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tungsten
      fonts:
        - asset: assets/fonts/Tungsten-Bold.ttf
    - family: DINNext
      fonts:
        - asset: assets/fonts/DINNextW1G-Medium.otf
    - family: FFMark
      fonts:
        - asset: assets/fonts/FontFont_FF.Mark.Pro.Black.otf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Proxima Nova Font.otf
    - family: Arial
      fonts:
        - asset: assets/fonts/ARIBL0.ttf
