name: valorant_intel
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

 
  assets:
    - assets/images/
  

  

  
  fonts:
    - family: Tungsten
      fonts:
        - asset: assets/fonts/Tungsten-Bold.ttf
    - family: DINNext
      fonts:
        - asset: assets/fonts/DINNextW1G-Medium.otf
    - family: FFMark
      fonts:
        - asset: assets/fonts/FontFont_FF.Mark.Pro.Black.otf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Proxima Nova Font.otf
    - family: Arial
      fonts:
        - asset: assets/fonts/ARIBL0.ttf
  