name: "Build"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
     
  push:
    branches:
      - master
      

jobs:
  build:
    name: Build Flutter Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable 

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > android/app/release-keystore.jks

      - name: Create key.properties
        run: |
          echo "storeFile=release-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

          
      - name: Install sdkmanager
        run: yes | sudo apt-get install -y android-sdk

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Build Signed APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
